@echo off

echo Desinstalando modulo tweepy ...
pip uninstall tweepy > nul

echo Desinstalando modulo pandas ...
pip uninstall pandas > nul

echo Desinstalando modulo imageio ...
pip uninstall imageio > nul

echo Desinstalando modulo sklearn ...
pip uninstall sklearn > nul

echo Desinstalando modulo flask ...
pip uninstall flask > nul

echo Desinstalando modulo flask_cors ...
pip uninstall flask_cors > nul

echo Desinstalando modulo wordcloud ...
pip uninstall wordcloud > nul

echo Desinstalando modulo geopy ...
pip uninstall geopy > nul

echo Desinstalando modulo folium ...
pip uninstall folium > nul